# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('newsPageLikeOrDislike', models.BooleanField(default=False)),
                ('sportPageLikeOrDislike', models.BooleanField(default=False)),
                ('bizPageLikeOrDislike', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('bizComments', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('newsComments', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('sportComments', models.CharField(max_length=5000)),
            ],
        ),
    ]
