# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=100)),
                ('key2', models.CharField(max_length=100)),
                ('nestedArr', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='bizPageLikeOrDislike',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='newsPageLikeOrDislike',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sportPageLikeOrDislike',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='accountArr',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
