# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20171213_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountArr',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='bizComments',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
