# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20171213_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
