# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_currentaccount_verifyaccount_verifylogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyAccount',
        ),
        migrations.DeleteModel(
            name='VerifyLogIn',
        ),
    ]
