# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_currentaccount_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentaccount',
            old_name='bizPageLikeOrDislike',
            new_name='bizPagelikeOrDislike',
        ),
        migrations.RenameField(
            model_name='currentaccount',
            old_name='newsPageLikeOrDislike',
            new_name='newsPagelikeOrDislike',
        ),
        migrations.RenameField(
            model_name='currentaccount',
            old_name='sportPageLikeOrDislike',
            new_name='sportPagelikeOrDislike',
        ),
    ]
