# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_auto_20171214_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='bizPagelikeOrDislike',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='newsPagelikeOrDislike',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='sportPagelikeOrDislike',
            field=models.CharField(max_length=100),
        ),
    ]
